services:
  candy:
    image: lanthora/candy
    container_name: "candy"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: always
    volumes:
      - ./data/candy:/var/lib/candy
  dae:
    image: daeuniverse/dae
    container_name: "dae"
    network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - /sys:/sys
      - ./config/dae:/etc/dae
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: candy dae --cleanup --log-level warn
